print("문자 선택 연산자에 대해 알아볼까요?")
print("안녕하세요"[0])
print("안녕하세요"[1])
print("안녕하세요"[2])
print("안녕하세요"[3])
print("안녕하세요"[4])
print()

print("반갑습니다"[-1])
print("반갑습니다"[-2])
print("반갑습니다"[-3])
print("반갑습니다"[-4])
print("반갑습니다"[-5])
print()